name: praxis_flutter
description: Praxis For Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  go_router: ^3.0.1

  flex_color_scheme: ^4.1.1
  google_fonts: ^2.2.0

  logging: ^1.0.2
  dio: ^4.0.4
  connectivity_plus: ^2.2.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.17

  shared_preferences: ^2.0.11
  flutter_local_notifications: ^9.2.0
  permission_handler: ^8.3.0
  share_plus: ^3.0.4
  equatable: ^2.0.3
  formz: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
#  assets:
#    - images/applogo.png