name: praxis_flutter
description: Praxis For Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^3.0.7
  clean_architecture:
    path: ./clean_architecture

  flex_color_scheme: ^4.2.0
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  logging: ^1.0.2
  dio: ^4.0.6
  connectivity_plus: ^2.2.1
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  equatable: ^2.0.3
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_analytics: ^9.1.3
  firebase_app_check: ^0.0.6+8
  firebase_messaging: ^11.2.12
  firebase_dynamic_links: ^4.1.2
  firebase_in_app_messaging: ^0.6.0+10
  firebase_app_installations: ^0.1.0+9
  google_sign_in: ^5.2.4
  praxis_flutter_domain:
    path: ./praxis_flutter_domain
  praxis_data:
    path: ./praxis_data
  flutter_local_notifications: ^9.4.0
  permission_handler: ^9.2.0
  shimmer: ^2.0.0
  uuid: ^3.0.6
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.4
  injectable_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - lang/
