# This is basic workflow to help you get started with Actions

name: Build,Test Release app to Firebase Hosting
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - name: Create Firebase options from secrets
        run: |
          echo FIREBASE_OPTIONS >> lib/firebase_options.dart
          cat lib/firebase_options.dart
        shell: bash
        env:
          FIREBASE_OPTIONS : ${{secrets.FIREBASE_OPTIONS}}
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Run flutter pub get'
        run: flutter pub get
      - name: 'Run Test(s)'
        run: flutter test
      - name: 'Build Android Apk'
        run: flutter clean && flutter build apk --release
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: developers
          file: build/app/outputs/flutter-apk/app-release.apk

  # This workflow contains a single job called "build"
  build_deploy_web:
    runs-on: ubuntu-latest

    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - name: Create Firebase options from secrets
        run: |
          echo FIREBASE_OPTIONS >> lib/firebase_options.dart
          cat lib/firebase_options.dart
        shell: bash
        env:
          FIREBASE_OPTIONS : ${{secrets.FIREBASE_OPTIONS}}
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Run flutter pub get'
        run: flutter pub get
      - name: 'Run Test(s)'
        run: flutter test
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: 'Build Web App'
        run: flutter build web
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}