# This is basic workflow to help you get started with Actions

name: Build,Test Release app to Firebase Hosting
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_apps:
    runs-on: macos-latest

    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Create Firebase options from secrets
        id: write_FIREBASE_OPTIONSIos
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'firebase_options.dart'
          fileDir: '/home/runner/work/PraxisFlutter/PraxisFlutter/lib/'
          encodedString: ${{ secrets.FIREBASE_OPTIONS }}
      - name: Create GoogleService-Info.plist from secrets
        id: write_fileGoogleServiceInfoIosPlist
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'GoogleService-Info.plist'
          fileDir: '/home/runner/work/PraxisFlutter/ios/'
          encodedString: ${{ secrets.GoogleServiceInfo }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Run flutter pub get'
        run: flutter pub get
      - name: 'Build iOS'
        run: flutter build ios --release --no-codesign
      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: 'Build Android Apk'
        run: flutter clean && flutter build apk --release
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: developers
          file: build/app/outputs/flutter-apk/app-release.apk
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: Build Web App
        run: |
          flutter build web
          cd build/web
          zip -r web-app.zip .
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa,build/web/web-app.zip'
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}